# Generated by Django 4.2.16 on 2024-09-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0196_slug_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.tag'),
        ),
    ]
