# Generated by Django 4.2.16 on 2024-09-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0198_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.tag'),
        ),
    ]
