# Generated by Django 4.2.16 on 2024-09-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0200_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
