# Generated by Django 4.2.16 on 2024-09-22 14:56

import django.contrib.postgres.indexes
from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0201_remove_wishlist_products_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='wishlist_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='wishlist_meta_idx'),
        ),
    ]
